#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""SRM采购协同 - 完整字段数据模块"""
# All modules with COMPLETE nested response fields
# Format: (level, field_name, description, data_type)

VM = {
'name':'供应商管理','interfaces':[
{'id':'1','name':'查询已加入的供应商列表','url':'https://openapi.xiekeyun.com/compVendor/confirmList.json','method':'POST','desc':'查询邀约状态为"已加入"的供应商列表数据',
 'params':[('erpCode','请求者用户ERP帐号','必填','String'),('innerVendorCode','供应商编码','选填','String'),('handshakeTimeStart','握手查询开始时间','选填','Number'),('handshakeTimeEnd','握手查询结束时间','选填','Number'),('categoryCode01','供应商分类1编码','选填','String'),('categoryCode02','供应商分类2编码','选填','String'),('categoryCode03','供应商分类3编码','选填','String'),('performanceClassificationCode','绩效分类编码','选填','String')],
 'responses':[(0,'result','返回结果状态 1:成功；9:失败','Number'),(0,'errorCode','接口错误编码(失败时有值)','String'),(0,'errorMsg','接口错误信息(失败时有值)','String'),(0,'dataList','供应商档案集合','Json数组'),(1,'vendorXkUniqueCode','供应商平台唯一编码','String'),(1,'innerVendorCode','供应商编码','String'),(1,'innerVendorName','供应商名称','String'),(1,'employeeName','邀约供应商的员工姓名','String'),(1,'handshakeTime','握手时间(时间戳)','Number'),(1,'categoryCode01','供应商分类1编码','String'),(1,'categoryName01','供应商分类1名称','String'),(1,'categoryCode02','供应商分类2编码','String'),(1,'categoryName02','供应商分类2名称','String'),(1,'categoryCode03','供应商分类3编码','String'),(1,'categoryName03','供应商分类3名称','String'),(1,'performanceClassificationCode','绩效分类编码','String'),(1,'performanceClassificationName','绩效分类名称','String')]},
{'id':'2','name':'查询供应商绩效考评结果','url':'https://openapi.xiekeyun.com/compVendor/assessmentScore.json','method':'POST','desc':'查询供应商月度绩效考评结果列表',
 'params':[('erpCode','请求者用户ERP帐号','必填','String'),('innerVendorCode','供应商编码','必填','String'),('innerVendorCodeList','供应商编码列表','必填','数组'),('timeType','绩效时间类型 1月份2季度3年份','必填','Number'),('yearTime','年份','必填','Number'),('yearType','年份类型','选填','Number'),('monthTime','月份 01-12','选填','String'),('quarterTime','季度 1-4','选填','Number')],
 'responses':[(0,'result','返回结果状态','Number'),(0,'errorCode','接口错误编码','String'),(0,'errorMsg','接口错误信息','String'),(0,'dataList','供应商绩效得分列表','Json对象'),(1,'innerVendorCode','内部供应商编码','String'),(1,'innerVendorName','内部供应商名称','String'),(1,'categoryCode','分类编码','String'),(1,'categoryName','分类名称','String'),(1,'assessmentMonth','绩效月份 yyyyMM','String'),(1,'assessmentScore','绩效得分','Number'),(1,'performanceScore','绩效评分','Number'),(1,'deductionScore','绩效扣分','Number'),(1,'gradeInfo','评级','String'),(1,'detailList','绩效明细项','json数组'),(2,'curSrcScore','本项达成率(%)','Number'),(2,'curTargetScore','本项得分','Number'),(2,'assementStandardItemCode','绩效考核项编码','String'),(2,'assementStandardItemName','绩效考核项名称','String'),(1,'vendorCategoryList','供应商分类列表','json数组'),(2,'categoryType','分类类型(0001-0004)','String'),(2,'categoryCode','分类编码','String'),(2,'categoryName','分类名称','String')]},
{'id':'3','name':'供应商档案详情','url':'https://openapi.xiekeyun.com/compVendor/getDetail.json','method':'POST','desc':'查询一个供应商详情明细数据',
 'params':[('erpCode','请求者用户ERP帐号','必填','String'),('innerVendorCode','供应商编码(ERP内)','必填','String')],
 'responses':[(0,'result','返回结果状态','Number'),(0,'errorCode','接口错误编码','String'),(0,'errorMsg','接口错误信息','String'),(0,'data','供应商详情','Json对象'),(1,'xkUniqueCode','内部供应商平台编码(32位)','String'),(1,'vendorCode','供应商携客企业号','String'),(1,'vendorName','企业名称','String'),(1,'vendorAbbr','企业简称','String'),(1,'innerVendorCode','内部供应商编码(ERP)','String'),(1,'innerVendorName','内部供应商名称','String'),(1,'innerVendorAbbr','内部供应商简称','String'),(1,'inviteStatus','邀约状态 0未发起1已发起2已确认3失败','Number'),(1,'handshakeTime','握手成功时间(时间戳)','Number'),(1,'vendorStatus','供应商状态 0无效1有效3黑名单','Number'),(1,'buyerCode','采购员编码','String'),(1,'buyerName','采购员名称','String'),(1,'buyerMobile','采购员手机号','String'),(1,'buyerEmail','采购员邮箱','String'),(1,'lifeCycle','生命周期 0准入评估1试样2小批量3正式4退出','Number'),(1,'gradeInfo','供应商绩效等级','String'),(1,'vendorCategoryCode','ERP分类编码','String'),(1,'vendorCategoryName','ERP分类名称','String'),(1,'creditCode','纳税人识别号','String'),(1,'paymentDaysCode','账期编码','String'),(1,'paymentDaysName','账期名称','String'),(1,'remark','备注','String'),(1,'contacts','联系人明细列表','Json对象数组'),(2,'fullName','姓名','String'),(2,'departmentName','部门名称','String'),(2,'positionName','职位名称','String'),(2,'phoneNo','联系电话','String'),(2,'mobile','手机号','String'),(2,'email','邮箱','String'),(2,'mainFlag','是否主要联系人 0否1是','Number'),(1,'vendorCategoryList','供应商分类/准入品类列表','Json对象数组'),(2,'categoryType','分类类型','String'),(2,'categoryCode','分类编码','String'),(2,'categoryName','分类名称','String'),(2,'status','状态 1有效2备用3暂停4退出','Number'),(1,'orgList','供应商组织关系列表','Json对象数组'),(2,'innerVendorCode','内部供应商编码','String'),(2,'isOverseasDirect','是否境外直送 0-否1-是','Number'),(2,'innerTradePartnerCode','贸易伙伴供应商编码','String'),(2,'innerTradePartnerName','贸易伙伴供应商名称','String'),(2,'purchaseOrgCode','采购组织编码','String'),(2,'purchaseOrgName','采购组织名称','String'),(2,'currencyCode','交易币种编码','String'),(2,'currencyName','交易币种名称','String'),(2,'payWayCode','付款条件编码','String'),(2,'payWayName','付款条件名称','String'),(2,'taxCode','交易税种编码','String'),(2,'taxName','交易税种名称','String'),(2,'deliveryTypeCode','交货方式编码','String'),(2,'deliveryTypeName','交货方式名称','String'),(2,'incoClauseCode','国际贸易条款编码','String'),(2,'status','有效否 0无效1有效','Number'),(2,'priceConditionList','价格条件列表','Json对象数组'),(3,'profitCenterCode','工厂编码','String'),(3,'profitCenterName','工厂名称','String'),(3,'erpPriceConditionCode','价格条件编码','String'),(3,'erpPriceConditionName','价格条件名称','String'),(3,'currencyCode','交易币种编码','String'),(3,'currencyName','交易币种名称','String'),(3,'payWayCode','付款条件编码','String'),(3,'payWayName','付款条件名称','String'),(1,'sqeList','SQE列表','Json对象数组'),(2,'sqeCode','SQE编码','String'),(2,'sqeName','SQE名称','String'),(1,'companyEnglishName','公司英文名称','String'),(1,'groupCompanyName','集团公司名称','String')]},
{'id':'4','name':'查询供应商应用度报表','url':'https://openapi.xiekeyun.com/compVendor/report.json','method':'POST','desc':'查询供应商应用报表数据',
 'params':[('erpCode','请求者用户ERP帐号','必填','Number'),('year','年份','必填','Number'),('month','月份','必填','Number'),('type','查询类型 1公司2组织','选填','Number')],
 'responses':[(0,'result','返回结果状态','Number'),(0,'errorCode','接口错误编码','String'),(0,'errorMsg','接口错误信息','String'),(0,'data','供应商应用度报表','Json对象'),(1,'reportMonth','报表月份 yyyyMM','String'),(1,'vendorTotalSum','供应商数量','Number'),(1,'vendorHandShakeSum','已握手供应商数量','Number'),(1,'reportList','供应商应用度报表列表','Json对象数组'),(2,'companyCode','企业号','String'),(2,'innerVendorCode','内部供应商编码','String'),(2,'innerVendorName','内部供应商名称','String'),(2,'currOrderSum','本月订单数','Number'),(2,'orderHandRate','订单处理率','Number'),(2,'onlineDeliveryRate','在线送货率','Number'),(2,'barPrintRate','条码打印率','Number'),(2,'onlineReconciliationRate','在线对账率','Number'),(2,'enquiryJoinRate','询价参与率','Number'),(2,'biddingJoinRate','竞价参与率','Number'),(2,'vendorCategoryCode','ERP供应商分类编码','String'),(2,'vendorCategoryName','ERP供应商分类名称','String')]},
{'id':'5','name':'查询集团法人绩效考评结果','url':'https://openapi.xiekeyun.com/compVendor/assessmentScore/relation/company/list.json','method':'POST','desc':'查询集团法人绩效考评结果列表',
 'params':[('erpCode','请求者用户ERP帐号','必填','String'),('innerVendorCode','供应商编码','必填','String'),('innerVendorCodeList','供应商编码列表','必填','数组'),('timeType','绩效时间类型','必填','Number'),('yearTime','年份','必填','Number'),('yearType','年份类型','选填','Number'),('monthTime','月份','选填','String'),('quarterTime','季度','选填','Number')],
 'responses':[(0,'result','返回结果状态','Number'),(0,'errorCode','接口错误编码','String'),(0,'errorMsg','接口错误信息','String'),(0,'dataList','供应商绩效得分列表','Json对象'),(1,'innerVendorCode','内部供应商编码','String'),(1,'innerVendorName','内部供应商名称','String'),(1,'assessmentScore','绩效得分','Number'),(1,'gradeInfo','评级','String'),(1,'detailList','绩效明细项','json数组'),(2,'curSrcScore','本项达成率(%)','Number'),(2,'curTargetScore','本项得分','Number'),(2,'assementStandardItemCode','绩效考核项编码','String'),(2,'assementStandardItemName','绩效考核项名称','String'),(1,'relationCompanyList','关联公司列表','json数组'),(2,'relationCompanyCode','关联企业编码','String'),(2,'relationCompanyName','关联企业名称','String'),(2,'assessmentScore','绩效总得分','Number'),(2,'gradeInfo','评级','String'),(2,'relAsDetailList','关联公司绩效明细','json数组'),(3,'curSrcScore','本项达成率(%)','Number'),(3,'curTargetScore','本项得分','Number'),(3,'assementStandardItemCode','绩效考核项编码','String'),(3,'assementStandardItemName','绩效考核项名称','String')]},
{'id':'6','name':'查询集团物料分类绩效考评结果','url':'https://openapi.xiekeyun.com/compVendor/assessmentScore/relation/company/prodCategory/list.json','method':'POST','desc':'查询集团物料分类绩效考评结果列表',
 'params':[('erpCode','请求者用户ERP帐号','必填','String'),('innerVendorCode','供应商编码','必填','String'),('innerVendorCodeList','供应商编码列表','必填','数组'),('timeType','绩效时间类型','必填','Number'),('yearTime','年份','必填','Number'),('yearType','年份类型','选填','Number'),('monthTime','月份','选填','String'),('quarterTime','季度','选填','Number')],
 'responses':[(0,'result','返回结果状态','Number'),(0,'errorCode','接口错误编码','String'),(0,'errorMsg','接口错误信息','String'),(0,'dataList','供应商绩效得分列表','Json对象'),(1,'prodCategoryCode','物料分类编码','String'),(1,'prodCategoryName','物料分类名称','String'),(1,'assessmentScore','绩效得分','Number'),(1,'gradeInfo','评级','String'),(1,'detailList','绩效明细项','json数组'),(2,'curSrcScore','本项达成率(%)','Number'),(2,'curTargetScore','本项得分','Number'),(2,'assementStandardItemCode','绩效考核项编码','String'),(2,'assementStandardItemName','绩效考核项名称','String'),(1,'vendorAsList','供应商列表','json数组'),(2,'innerVendorCode','供应商编码','String'),(2,'innerVendorName','供应商名称','String'),(2,'assessmentScore','绩效总得分','Number'),(2,'gradeInfo','评级','String'),(2,'vendorDetailList','供应商绩效明细','json数组'),(3,'curSrcScore','本项达成率(%)','Number'),(3,'curTargetScore','本项得分','Number'),(3,'assementStandardItemCode','绩效考核项编码','String'),(3,'assementStandardItemName','绩效考核项名称','String')]}]}

if __name__ == '__main__':
    print('VM loaded')
